import React, { useEffect, useState } from 'react';
import { Copy, Share2 } from 'lucide-react';
import { barberAPI, publicAPI, staffAppointmentAPI } from '../api';
import { ActionButton, SurfaceCard } from './design';

const today = () => new Date().toISOString().slice(0, 10);

export default function StaffWalkinBooking({ onDone, onClose }) {
  const [profile, setProfile] = useState(null), [services, setServices] = useState([]), [slots, setSlots] = useState([]);
  const [form, setForm] = useState({ service_id: '', date: today(), time: '', client_name: '', client_phone: '', client_email: '' });
  const [success, setSuccess] = useState(null), [error, setError] = useState(''), [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { try { const p = (await barberAPI.getMyProfile()).data; setProfile(p); setServices((await publicAPI.getServices(p.organization_id)).data || []); } catch (_) { setError('No fue posible cargar tu agenda.'); } })(); }, []);
  useEffect(() => { if (!profile || !form.service_id || !form.date) return; publicAPI.getAvailability(profile.organization_id, profile.barber_id, form.date, form.service_id).then(r => setSlots(r.data?.available_slots || r.data?.slots || [])).catch(() => setSlots([])); }, [profile, form.service_id, form.date]);
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const submit = async event => { event.preventDefault(); setSaving(true); setError(''); try { const response = await staffAppointmentAPI.createWalkin(form); setSuccess(response.data); onDone?.(); } catch (err) { setError(err?.response?.data?.detail?.message || err?.response?.data?.detail || 'No fue posible crear la cita.'); } finally { setSaving(false); } };
  const portal = profile ? `${window.location.origin}/portal/${profile.organization_id}` : '';
  if (success) return <SurfaceCard><h2>Cita confirmada</h2><p>Para la próxima vez, comparte el portal del cliente. Sus datos se usan solo para gestionar esta cita.</p><div className="flex gap-2 flex-wrap"><ActionButton variant="secondary" icon={Copy} onClick={() => navigator.clipboard?.writeText(portal)}>Copiar enlace</ActionButton><ActionButton variant="secondary" icon={Share2} onClick={() => navigator.share?.({ title: 'Portal de clientes', text: `Para tu próxima cita usa ${portal}`, url: portal })}>Compartir por WhatsApp</ActionButton><ActionButton onClick={() => onClose?.()}>Cerrar</ActionButton></div></SurfaceCard>;
  return <SurfaceCard><div className="flex justify-between gap-3"><div><h2>Nueva cita</h2><p className="text-sm">Cliente presencial · sin consentimiento de marketing.</p></div><button type="button" onClick={onClose}>Cerrar</button></div><form onSubmit={submit} className="nexus-form-grid mt-4"><label>Servicio<select className="nexus-field" required value={form.service_id} onChange={e => set('service_id', e.target.value)}><option value="">Selecciona</option>{services.map(item => <option key={item.service_id} value={item.service_id}>{item.name}</option>)}</select></label><label>Fecha<input className="nexus-field" type="date" min={today()} required value={form.date} onChange={e => set('date', e.target.value)}/></label><label>Hora<select className="nexus-field" required value={form.time} onChange={e => set('time', e.target.value)}><option value="">Selecciona</option>{slots.map(slot => <option key={slot} value={slot}>{slot}</option>)}</select></label><label>Teléfono<input className="nexus-field" required value={form.client_phone} onChange={e => set('client_phone', e.target.value)}/></label><label>Nombre<input className="nexus-field" required value={form.client_name} onChange={e => set('client_name', e.target.value)}/></label><label>Correo (opcional)<input className="nexus-field" type="email" value={form.client_email} onChange={e => set('client_email', e.target.value)}/></label>{error && <p role="alert" className="text-amber-400 text-sm">{error}</p>}<ActionButton loading={saving}>Confirmar cita</ActionButton></form></SurfaceCard>;
}
