import React,{useCallback,useEffect,useState} from 'react';
import {AlertTriangle,Trash2,X} from 'lucide-react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {ActionButton} from './ActionButton';
import {useAccessibleDialog} from './useAccessibleDialog';
// NEXUS_ADMIN_OPERATIONS_COMPLETION_V2
// NEXUS_ACCESSIBILITY_4A_V1
let listener=null;
export function confirmAction(message,options={}){return new Promise(resolve=>{if(!listener){resolve(false);return}listener({message,...options,resolve});});}
export function ConfirmDialogHost(){const [request,setRequest]=useState(null);const reduced=useReducedMotion();useEffect(()=>{listener=value=>setRequest(value);return()=>{listener=null}},[]);const close=useCallback(value=>{setRequest(current=>{if(!current)return null;current.resolve(value);return null})},[]);const dismiss=useCallback(()=>close(false),[close]);const {dialogRef,titleId,descriptionId}=useAccessibleDialog({open:!!request,onClose:dismiss,titlePrefix:'nexus-confirm'});return <AnimatePresence>{request&&<div className="nexus-confirm-dialog"><motion.button className="nexus-confirm-backdrop" aria-label="Cerrar" onClick={dismiss} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.section ref={dialogRef} role="alertdialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={-1} initial={reduced?false:{opacity:0,scale:.96,y:16}} animate={{opacity:1,scale:1,y:0}} exit={reduced?undefined:{opacity:0,scale:.98,y:10}} transition={{type:'spring',stiffness:420,damping:34}}><header><span className={request.tone==='warning'?'is-warning':'is-danger'}>{request.tone==='warning'?<AlertTriangle size={21}/>:<Trash2 size={21}/>}</span><button type="button" onClick={dismiss} aria-label="Cerrar"><X size={18}/></button></header><h2 id={titleId}>{request.title||'Confirmar acción'}</h2><p id={descriptionId}>{request.message}</p><footer><ActionButton variant="secondary" onClick={dismiss}>Cancelar</ActionButton><ActionButton variant={request.tone==='warning'?'primary':'destructive'} onClick={()=>close(true)}>{request.confirmLabel||'Confirmar'}</ActionButton></footer></motion.section></div>}</AnimatePresence>;}
