// NEXUS_8A7D3B_PROFESSIONAL_IMAGE_UPLOAD_V1
import React,{useEffect,useRef,useState} from 'react';
import {ImagePlus,Trash2,UploadCloud} from 'lucide-react';
import {ActionButton} from './ActionButton';

const TYPES=['image/jpeg','image/png','image/webp'];
const LIMIT=5*1024*1024;
export function ProfessionalImageUpload({value,name='Profesional',onUpload,onDelete,onChange,disabled=false,lockedMessage=''}){
 const inputRef=useRef(null),objectUrlRef=useRef('');const [preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[dragging,setDragging]=useState(false);
 useEffect(()=>()=>{if(objectUrlRef.current)URL.revokeObjectURL(objectUrlRef.current)},[]);
 const choose=async file=>{setError('');if(!file)return;if(!TYPES.includes(file.type)){setError('Selecciona una imagen JPG, PNG o WebP.');return}if(file.size>LIMIT){setError('La imagen no puede superar 5 MB.');return}if(objectUrlRef.current)URL.revokeObjectURL(objectUrlRef.current);objectUrlRef.current=URL.createObjectURL(file);setPreview(objectUrlRef.current);setBusy(true);setProgress(0);try{const response=await onUpload(file,value=>setProgress(Math.max(0,Math.min(100,value))));const avatar=response?.data?.avatar||response?.avatar;if(!avatar)throw new Error('missing avatar');onChange(avatar);setPreview('')}catch(e){setPreview('');setError(e?.response?.data?.detail||'No fue posible cargar la imagen.')}finally{setBusy(false);setProgress(0);if(inputRef.current)inputRef.current.value=''}};
 const remove=async()=>{if(!value||busy)return;if(!window.confirm('¿Eliminar la fotografía profesional?'))return;setBusy(true);setError('');try{await onDelete();onChange('')}catch(e){setError(e?.response?.data?.detail||'No fue posible eliminar la imagen.')}finally{setBusy(false)}};
 const drop=e=>{e.preventDefault();setDragging(false);if(!disabled&&!lockedMessage)choose(e.dataTransfer.files?.[0])};
 const image=preview||value;
 return <section className="sm:col-span-2 space-y-3"><div className={`rounded-2xl border-2 border-dashed p-4 transition-colors ${dragging?'border-[#0A84FF] bg-[#0A84FF]/10':'border-[var(--app-border)] bg-white/3'}`} onDragOver={e=>{e.preventDefault();if(!disabled&&!lockedMessage)setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} aria-busy={busy}><div className="flex flex-col sm:flex-row items-center gap-4">{image?<img src={image} alt={`Fotografía de ${name}`} className="h-24 w-24 rounded-2xl object-cover border border-[var(--app-border)]"/>:<span className="h-24 w-24 rounded-2xl grid place-items-center bg-white/5 text-zinc-500"><ImagePlus size={30}/></span>}<div className="flex-1 text-center sm:text-left"><strong className="block text-[var(--app-text-primary)]">Fotografía profesional</strong><p className="text-sm text-zinc-500 mt-1">Arrastra una imagen o selecciónala. JPG, PNG o WebP, máximo 5 MB.</p>{lockedMessage&&<p className="text-sm text-amber-400 mt-2" role="status">{lockedMessage}</p>}<div className="flex flex-wrap justify-center sm:justify-start gap-2 mt-3"><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>choose(e.target.files?.[0])} disabled={disabled||busy||!!lockedMessage}/><ActionButton icon={UploadCloud} variant="secondary" disabled={disabled||busy||!!lockedMessage} onClick={()=>inputRef.current?.click()}>{value?'Reemplazar':'Seleccionar imagen'}</ActionButton>{value&&<ActionButton icon={Trash2} variant="destructive" disabled={disabled||busy} onClick={remove}>Eliminar</ActionButton>}</div></div></div>{busy&&<div className="mt-3" role="status" aria-live="polite"><div className="h-2 rounded-full bg-white/10 overflow-hidden"><span className="block h-full bg-[#0A84FF] transition-all" style={{width:`${progress||8}%`}}/></div><small className="text-zinc-400">Procesando imagen{progress?` ${progress}%`:'...'}</small></div>}</div>{error&&<p className="text-sm text-red-400" role="alert">{error}</p>}</section>;
}
