import React, { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, LockKeyhole, LogOut, ShieldCheck, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { authAPI } from '../api';
import { useAuth } from '../context/AuthContext';
import { AccessibleModal, ActionButton, MotionPage, PageHeader, SurfaceCard } from '../components/design';

// NEXUS_ACCOUNT_SAFETY_V1
const PHRASE='ELIMINAR MI CUENTA';
export default function AccountPrivacy(){
 const {user,logout}=useAuth();const navigate=useNavigate();const [open,setOpen]=useState(false);const [password,setPassword]=useState('');const [confirmation,setConfirmation]=useState('');const [understood,setUnderstood]=useState(false);const [busy,setBusy]=useState(false);
 const manual=!!user?.auth_method&&user.auth_method==='manual';const ready=useMemo(()=>confirmation===PHRASE&&understood&&(!manual||password.length>0),[confirmation,understood,manual,password]);
 const signOut=async()=>{await logout();navigate('/login',{replace:true})};
 const remove=async()=>{if(!ready||busy)return;setBusy(true);try{await authAPI.deleteAccount({confirmation,password:manual?password:null,understood});toast.success('Tu cuenta fue eliminada');await logout();navigate('/login',{replace:true})}catch(error){toast.error(error.response?.data?.detail||'No fue posible eliminar la cuenta')}finally{setBusy(false)}};
 return <div className="nexus-screen"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-8"><MotionPage className="space-y-6"><PageHeader eyebrow="Seguridad" title="Cuenta y privacidad" description="Administra tu sesión y el tratamiento de tu cuenta." actions={<ActionButton variant="secondary" icon={ArrowLeft} onClick={()=>navigate(-1)}>Volver</ActionButton>}/><div className="grid lg:grid-cols-2 gap-5"><SurfaceCard><span className="nexus-security-icon"><ShieldCheck size={22}/></span><h2 className="text-xl mt-4">Sesión</h2><p className="text-[var(--app-text-secondary)] mt-2 mb-5">Cierra tu sesión en este dispositivo cuando termines de trabajar.</p><ActionButton icon={LogOut} onClick={signOut}>Cerrar sesión</ActionButton></SurfaceCard><SurfaceCard><span className="nexus-security-icon nexus-security-danger"><Trash2 size={22}/></span><h2 className="text-xl mt-4">Eliminar cuenta</h2><p className="text-[var(--app-text-secondary)] mt-2">Desactiva el acceso, elimina datos del perfil y anonimiza referencias históricas que deban conservarse.</p>{user?.role==='owner'&&<div className="nexus-account-warning"><AlertTriangle size={18}/><span>El último Owner debe transferir la propiedad antes de eliminar su cuenta.</span></div>}<ActionButton variant="destructive" icon={Trash2} onClick={()=>setOpen(true)}>Solicitar eliminación</ActionButton></SurfaceCard></div>{open&&<AccessibleModal open={open} onClose={()=>!busy&&setOpen(false)} role="alertdialog" labelledBy="account-delete-title" describedBy="account-delete-description" className="nexus-account-modal" panelClassName="nexus-accessible-modal-panel"><span className="nexus-security-icon nexus-security-danger"><LockKeyhole size={22}/></span><h2 id="account-delete-title">Confirmar eliminación</h2><p id="account-delete-description">Esta acción cerrará todas tus sesiones, desactivará perfiles profesionales vinculados y bloqueará el acceso futuro.</p>{manual&&<label>Contraseña actual<input className="nexus-field" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>}<label>Escribe exactamente <strong>{PHRASE}</strong><input className="nexus-field" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><label className="nexus-account-check"><input type="checkbox" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/><span>Entiendo que perderé el acceso y que algunos registros financieros o de auditoría pueden conservarse anonimizados.</span></label><div className="nexus-account-actions"><ActionButton variant="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancelar</ActionButton><ActionButton variant="destructive" loading={busy} disabled={!ready} onClick={remove}>Eliminar definitivamente</ActionButton></div></AccessibleModal>}</MotionPage></div></div>;
}
