import React,{useEffect,useState} from 'react';
import {useParams,useSearchParams} from 'react-router-dom';
import {CalendarDays,CheckCircle,Clock,Scissors,UserRound,XCircle} from 'lucide-react';
import {publicAPI} from '../api';
import {ActionButton,LoadingState,StatusBadge,confirmAction} from '../components/design';

// NEXUS_HARDENING_3C_V1
export default function CancelAppointment(){
 const {appointmentId}=useParams();const [searchParams]=useSearchParams();const token=searchParams.get('token')||'';const [appointment,setAppointment]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[cancelling,setCancelling]=useState(false);
 useEffect(()=>{let active=true;if(!appointmentId||!token){setError('Este enlace no es válido o está incompleto.');setLoading(false);return undefined}publicAPI.getAppointment(appointmentId,token).then(r=>{if(active)setAppointment(r.data)}).catch(e=>{if(active)setError(e.response?.data?.detail||'No fue posible validar este enlace.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[appointmentId,token]);
 const handleCancel=async()=>{const accepted=await confirmAction('La cita quedará cancelada y el horario volverá a estar disponible.',{title:'Cancelar cita',confirmLabel:'Cancelar cita'});if(!accepted)return;setCancelling(true);setError('');try{await publicAPI.cancelAppointment(appointmentId,token);setAppointment(x=>({...x,status:'cancelled'}))}catch(e){setError(e.response?.data?.detail||'No fue posible cancelar la cita.')}finally{setCancelling(false)}};
 if(loading)return <LoadingState label="Validando enlace de cita"/>;
 return <main className="nexus-cancel-page"><section><header><small>Gestión segura</small><h1>Gestionar cita</h1><p>Consulta los detalles y cancela únicamente si es necesario.</p></header>{error&&<div className="nexus-public-error">{error}</div>}{appointment&&<><div className="nexus-cancel-status"><StatusBadge tone={appointment.status==='cancelled'?'danger':appointment.status==='completed'?'success':'info'}>{appointment.status==='cancelled'?'Cancelada':appointment.status==='completed'?'Completada':'Confirmada'}</StatusBadge></div><div className="nexus-cancel-details"><div><CalendarDays/><span>Fecha<strong>{appointment.date}</strong></span></div><div><Clock/><span>Hora<strong>{appointment.time}</strong></span></div><div><Scissors/><span>Servicio<strong>{appointment.service_name}</strong></span></div><div><UserRound/><span>Profesional<strong>{appointment.barber_name}</strong></span></div></div>{appointment.status==='cancelled'?<div className="nexus-cancel-result"><XCircle/>Esta cita ya está cancelada.</div>:appointment.status==='completed'?<div className="nexus-cancel-result is-success"><CheckCircle/>Las citas completadas no se pueden cancelar.</div>:<ActionButton variant="destructive" loading={cancelling} onClick={handleCancel}>Cancelar cita</ActionButton>}</>}</section></main>;
}
