import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {CalendarDays,Clock,ExternalLink,Loader2,LogOut,MapPin,Phone,Scissors,UserRound,Trash2} from 'lucide-react';
import PhoneInput from 'react-phone-number-input';
import 'react-phone-number-input/style.css';
import {toast} from 'sonner';
import {publicAPI} from '../api';import {useOrganization} from '../context/OrganizationContext';import {ActionButton,EmptyState,StatusBadge,confirmAction} from '../components/design';
import ClientPortalNav from '../components/ClientPortalNav';
// NEXUS_PUBLIC_DEEP_FINAL_V1
const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v)||0);const tone={confirmed:'info',completed:'success',cancelled:'danger'};const label={confirmed:'Confirmada',completed:'Completada',cancelled:'Cancelada'};
export default function CustomerPortal(){const {orgId}=useParams();const navigate=useNavigate();const {organization,loadOrganization}=useOrganization();const [view,setView]=useState('login'),[phone,setPhone]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(false),[client,setClient]=useState(null),[appointments,setAppointments]=useState([]),[historyLoading,setHistoryLoading]=useState(false);
 const loadHistory=useCallback(async value=>{setHistoryLoading(true);try{const response=await publicAPI.getClientHistory(value,orgId);setAppointments(response.data.appointments||[])}catch{setAppointments([])}finally{setHistoryLoading(false)}},[orgId]);
 const login=useCallback(async(value=phone,skip=false)=>{if(!value||value.length<10)return toast.error('Ingresa un teléfono válido');setLoading(true);try{const response=await publicAPI.passwordlessAuth({phone:value,organization_id:orgId,name:name||undefined});if(!skip)sessionStorage.setItem(`nexus_customer_phone_${orgId}`,value);setClient(response.data.client);setView('portal');toast.success(response.data.message);await loadHistory(value)}catch(error){toast.error(error.response?.data?.detail==='name_required'?'Ingresa tu nombre para crear el perfil':error.response?.data?.detail||'No fue posible ingresar')}finally{setLoading(false)}},[phone,name,orgId,loadHistory]);
 useEffect(()=>{loadOrganization(orgId);const saved=sessionStorage.getItem(`nexus_customer_phone_${orgId}`);if(saved){setPhone(saved);login(saved,true)}},[orgId,loadOrganization,login]);
 const future=useMemo(()=>appointments.filter(x=>x.status==='confirmed'&&`${x.date}T${x.time}`>=new Date().toISOString().slice(0,16)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)),[appointments]);const next=future[0];
 const logout=()=>{sessionStorage.removeItem(`nexus_customer_phone_${orgId}`);setView('login');setClient(null);setAppointments([]);setPhone('');setName('')};
 // Eliminar cuenta deshabilitado en portal legacy - usar portal con PIN en /portal/:orgId/auth
 const handleDeleteAccount=async()=>{toast.error('Esta función requiere iniciar sesión en el portal seguro');};
 if(view==='login')return <div className="nexus-portal-login"><ClientPortalNav orgId={orgId} /><section><span className="nexus-choice-icon"><UserRound/></span><small>{organization?.name||'Portal del cliente'}</small><h1>Consulta tus citas</h1><p>Ingresa con el teléfono utilizado en la reserva.</p><label>Teléfono<PhoneInput international defaultCountry="CO" value={phone} onChange={setPhone}/></label><label>Nombre, solo si eres cliente nuevo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre completo"/></label><ActionButton loading={loading} onClick={()=>login()}>Ingresar al portal</ActionButton><button className="nexus-text-link" onClick={()=>navigate(`/book/${orgId}`)}>¿Primera vez? Reserva una cita</button></section></div>;
 return <div className="nexus-portal-deep"><ClientPortalNav orgId={orgId} /><header><div><small>Portal del cliente</small><h1>Hola, {client?.name}</h1></div><div style={{display:'flex',gap:'0.5rem'}}><ActionButton variant="secondary" icon={LogOut} onClick={logout}>Salir</ActionButton><ActionButton variant="destructive" icon={Trash2} loading={loading} onClick={handleDeleteAccount}>Eliminar cuenta</ActionButton></div></header><div className="nexus-portal-grid"><main>{next?<section className="nexus-next-appointment"><small>Próxima cita</small><div><span><CalendarDays/></span><div><h2>{next.service_name}</h2><p>{next.date} · {next.time}</p></div><StatusBadge tone="info">Confirmada</StatusBadge></div><dl><div><dt>Profesional</dt><dd>{next.barber_name}</dd></div><div><dt>Valor</dt><dd>{money(next.service_price)}</dd></div></dl><ActionButton icon={CalendarDays} onClick={()=>navigate(`/book/${orgId}`)}>Reservar otra cita</ActionButton></section>:<section className="nexus-portal-card"><EmptyState icon={CalendarDays} title="No tienes próximas citas" description="Cuando reserves una cita aparecerá aquí."/><ActionButton onClick={()=>navigate(`/book/${orgId}`)}>Reservar cita</ActionButton></section>}<section className="nexus-portal-card"><div className="nexus-section-heading"><div><h2>Historial</h2><p>{appointments.length} citas registradas</p></div></div>{historyLoading?<div className="nexus-skeleton-row"/>:appointments.length?<div className="nexus-portal-history">{appointments.map(item=><article key={item.appointment_id}><span className="nexus-choice-icon"><Scissors size={18}/></span><div><strong>{item.service_name}</strong><p><UserRound size={13}/>{item.barber_name}</p><small><CalendarDays size={13}/>{item.date}<Clock size={13}/>{item.time}</small></div><div><b>{money(item.service_price)}</b><StatusBadge tone={tone[item.status]||'neutral'}>{label[item.status]||item.status}</StatusBadge></div></article>)}</div>:<EmptyState title="Sin historial" description="Aún no hay citas registradas."/>}</section></main><aside><section className="nexus-portal-card nexus-client-card"><span className="nexus-avatar">{client?.name?.charAt(0)}</span><h2>{client?.name}</h2><p><Phone size={14}/>{client?.phone}</p><div><span>Visitas</span><strong>{client?.total_visits||0}</strong></div>{client?.last_visit&&<div><span>Última visita</span><strong>{client.last_visit}</strong></div>}</section>{organization&&<section className="nexus-portal-card"><h2>{organization.name}</h2>{organization.address&&<p><MapPin size={15}/>{organization.address}</p>}{organization.phone&&<p><Phone size={15}/>{organization.phone}</p>}{organization.business_hours&&<p><Clock size={15}/>{organization.business_hours}</p>}{organization.whatsapp_link&&<ActionButton variant="secondary" icon={ExternalLink} onClick={()=>window.open(organization.whatsapp_link,'_blank','noopener,noreferrer')}>Contactar</ActionButton>}</section>}</aside></div></div>}
