import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {appointmentAPI,organizationAPI,serviceAPI,barberAPI,transactionAPI} from '../api';
import {CalendarDays,DollarSign,Scissors,Users,WalletCards,LogOut,Plus,Clock3} from 'lucide-react';
import DashboardStats from '../components/DashboardStats';
import BookingTools from '../components/BookingTools';
import WeeklyCalendar from '../components/WeeklyCalendar';
import {AdminShell,ActionButton,AnimatedNumber,EmptyState,MetricCard,MotionPage,PageHeader,SegmentedControl,SurfaceCard} from '../components/design';

// NEXUS_SHELL_INTEGRATION_V1
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(value)||0);
export default function ManagerDashboard(){
 const {user,logout}=useAuth();const navigate=useNavigate();const [sp,setSp]=useSearchParams();
 const [appointments,setAppointments]=useState([]),[organizations,setOrganizations]=useState([]),[selectedOrg,setSelectedOrg]=useState(null),[services,setServices]=useState([]),[barbers,setBarbers]=useState([]),[todayRevenue,setTodayRevenue]=useState(0),[loading,setLoading]=useState(true),[filter,setFilter]=useState('all');
 const loadOrgData=useCallback(async orgId=>{const params=user.role==='owner'?{organization_id:orgId}:{};const today=new Date().toISOString().split('T')[0];const [a,s,b,r]=await Promise.all([appointmentAPI.getToday(params),serviceAPI.getAll(params),barberAPI.getAll(params),transactionAPI.getSummary({...params,start_date:today,end_date:today})]);setAppointments(a.data||[]);setServices(s.data||[]);setBarbers(b.data||[]);setTodayRevenue(Number(r.data?.total_received)||0)},[user.role]);
 const load=useCallback(async()=>{setLoading(true);try{const response=await organizationAPI.getAll();setOrganizations(response.data||[]);const requested=sp.get('org_id');const target=user.role==='owner'?(response.data.find(item=>item.organization_id===requested)||response.data[0]):response.data.find(item=>item.organization_id===user.organization_id);if(target){setSelectedOrg(target);await loadOrgData(target.organization_id)}}finally{setLoading(false)}},[loadOrgData,sp,user.organization_id,user.role]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>appointments.filter(item=>filter==='all'||(filter.startsWith('service_')&&item.service_id===filter.replace('service_',''))||(filter.startsWith('barber_')&&item.barber_id===filter.replace('barber_',''))),[appointments,filter]);
 const changeOrg=async id=>{const org=organizations.find(item=>item.organization_id===id);setSelectedOrg(org);setSp({org_id:id});await loadOrgData(id)};
 const signOut=async()=>{await logout();navigate('/login')};
 if(user?.access_status!=='approved')return <div className="nexus-screen grid place-items-center p-6"><SurfaceCard className="max-w-md text-center"><h2 className="text-2xl mb-3">Cuenta pendiente de aprobación</h2><p className="text-[var(--app-text-secondary)] mb-6">La administración debe aprobar el acceso.</p><ActionButton onClick={signOut}>Cerrar sesión</ActionButton></SurfaceCard></div>;
 if(loading)return <div className="nexus-screen grid place-items-center"><div className="nexus-skeleton-row w-72"/></div>;
 if(!selectedOrg)return <div className="nexus-screen grid place-items-center"><EmptyState title="No hay una organización disponible" description="Crea o solicita acceso a una organización para continuar."/></div>;
 const orgId=selectedOrg.organization_id;
 return <AdminShell organizationName={selectedOrg.name} organizationId={orgId} actions={<ActionButton variant="ghost" icon={LogOut} onClick={signOut}>Salir</ActionButton>}><MotionPage className="space-y-7"><PageHeader eyebrow="Centro de operaciones" title={`Buenos días, ${user?.name?.split(' ')[0]||'equipo'}`} description="Agenda, ingresos y actividad del negocio en un solo lugar." actions={<ActionButton icon={Plus} onClick={()=>navigate(`/manager/appointments?org_id=${orgId}`)}>Nueva cita</ActionButton>}/>
 {user.role==='owner'&&organizations.length>1&&<SurfaceCard className="max-w-sm"><label className="text-xs font-semibold text-[var(--app-text-muted)]">ORGANIZACIÓN</label><select value={orgId} onChange={event=>changeOrg(event.target.value)} className="nexus-field mt-2">{organizations.map(org=><option key={org.organization_id} value={org.organization_id}>{org.name}</option>)}</select></SurfaceCard>}
 <section className="grid grid-cols-2 xl:grid-cols-4 gap-3"><MetricCard index={0} label="Citas de hoy" value={<AnimatedNumber value={appointments.length} format={value=>Math.round(value)}/>} icon={CalendarDays}/><MetricCard index={1} label="Ingresos de hoy" value={<AnimatedNumber value={todayRevenue} format={money}/>} icon={DollarSign}/><MetricCard index={2} label="Profesionales activos" value={<AnimatedNumber value={new Set(appointments.map(item=>item.barber_id)).size} format={value=>Math.round(value)}/>} icon={Users}/><MetricCard index={3} label="Servicios disponibles" value={<AnimatedNumber value={services.length} format={value=>Math.round(value)}/>} icon={Scissors}/></section>
 <section className="grid xl:grid-cols-[1.15fr_.85fr] gap-6"><SurfaceCard><div className="nexus-section-heading"><div><h2>Agenda de hoy</h2><p>{filtered.length} citas visibles</p></div><SegmentedControl value={filter} onChange={setFilter} options={[{value:'all',label:'Todas'},...barbers.slice(0,3).map(item=>({value:`barber_${item.barber_id}`,label:item.display_name||item.name}))]}/></div>{filtered.length? <div className="nexus-timeline">{filtered.slice(0,6).map(item=><article key={item.appointment_id}><time>{item.time}</time><span className="nexus-timeline-dot"/><div><strong>{item.client_name}</strong><p>{item.service_name} · {item.barber_name}</p></div><b>{money(item.service_price)}</b></article>)}</div>:<EmptyState icon={Clock3} title="No hay citas para este filtro" description="La agenda aparecerá aquí cuando existan reservas."/>}</SurfaceCard><SurfaceCard><div className="nexus-section-heading"><div><h2>Acciones rápidas</h2><p>Atajos operativos</p></div></div><div className="nexus-quick-grid"><ActionButton icon={CalendarDays} onClick={()=>navigate(`/manager/appointments?org_id=${orgId}`)}>Abrir agenda</ActionButton><ActionButton variant="secondary" icon={Users} onClick={()=>navigate(`/manager/clients?org_id=${orgId}`)}>Clientes</ActionButton><ActionButton variant="secondary" icon={WalletCards} onClick={()=>navigate(`/manager/revenue?org_id=${orgId}`)}>Ingresos</ActionButton><ActionButton variant="secondary" icon={Scissors} onClick={()=>navigate(`/manager/services?org_id=${orgId}`)}>Servicios</ActionButton></div></SurfaceCard></section>
 <BookingTools organizationId={orgId}/><DashboardStats organizationId={orgId}/><WeeklyCalendar organizationId={orgId}/></MotionPage></AdminShell>;
}
