// NEXUS_8A7D1A_VISIBLE_NEUTRAL_TERMINOLOGY_V1
/* NEXUS_8A2_MANAGER_FISCAL_ONBOARDING_V1 */
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Building2,RefreshCw,Save,ShieldCheck} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {toast} from 'sonner';
import {billingAPI} from '../api';
import {useAuth} from '../context/AuthContext';
import {ActionButton,FieldGuide,LoadingState,MotionPage,PageHeader,StatusBadge,SurfaceCard} from '../components/design';

const emptyProfile={billing_email:'',billing_contact_name:'',billing_contact_phone:'',person_type:'',commercial_name:'',legal_name:'',document_type:'',tax_id:'',verification_digit:'',tax_responsibility:'',tax_regime:'',country:'Colombia',department:'',city:'',address:'',postal_code:'',fiscal_notes:'',cc_emails:'',copy_primary_manager:true,email_enabled:true,profile_version:0,profile_status:'incomplete',missing_required_fields:[]};
const fieldLabels={legal_name:'Razón social',document_type:'Tipo de documento',tax_id:'Número de identificación',billing_email:'Correo de facturación',city:'Ciudad',address:'Dirección'};
const detail=(error,fallback)=>{const value=error?.response?.data?.detail;if(typeof value==='string')return value;if(value?.message)return value.message;return fallback};
const normalizeLoaded=value=>({...emptyProfile,...value,cc_emails:(value?.cc_emails||[]).join(', '),missing_required_fields:value?.missing_required_fields||[]});

export default function ManagerFiscalProfile(){
 const {user}=useAuth();const [searchParams]=useSearchParams();
 const organizationId=(user?.role==='owner'?searchParams.get('org_id'):user?.organization_id)||user?.organization_id;
 const [profile,setProfile]=useState(emptyProfile),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[reason,setReason]=useState('Actualización de información fiscal de la organización');
 const params=useMemo(()=>user?.role==='owner'&&organizationId?{organization_id:organizationId}:{},[user?.role,organizationId]);
 const load=useCallback(async()=>{if(!organizationId){setLoading(false);return}setLoading(true);try{const response=await billingAPI.getProfile(params);setProfile(normalizeLoaded(response.data||{}))}catch(error){toast.error(detail(error,'No fue posible cargar la información fiscal'))}finally{setLoading(false)}},[organizationId,params]);
 useEffect(()=>{load()},[load]);
 const set=(key,value)=>setProfile(current=>({...current,[key]:value}));
 const save=async event=>{event.preventDefault();if(reason.trim().length<3)return toast.error('Indica un motivo de al menos 3 caracteres');setSaving(true);try{const payload={...profile,cc_emails:String(profile.cc_emails||'').split(',').map(value=>value.trim()).filter(Boolean),expected_version:Number(profile.profile_version||0),change_reason:reason.trim()};delete payload.profile_status;delete payload.missing_required_fields;delete payload.organization_id;delete payload.updated_at;delete payload.updated_by;delete payload.created_at;delete payload.created_by;delete payload.email_source;const response=await billingAPI.saveProfile(payload,params);setProfile(normalizeLoaded(response.data||{}));toast.success('Información fiscal guardada y auditada')}catch(error){if(error?.response?.status===409){toast.error('El perfil cambió en otra sesión. Recarga antes de volver a guardar.')}else toast.error(detail(error,'No fue posible guardar la información fiscal'))}finally{setSaving(false)}};
 if(loading)return <LoadingState label="Cargando información fiscal"/>;
 if(!organizationId)return <MotionPage><PageHeader eyebrow="Información fiscal" title="Organización no disponible" description="Selecciona una organización válida para continuar."/></MotionPage>;
 const missing=profile.missing_required_fields||[];
 return <MotionPage className="space-y-6"><PageHeader eyebrow="Administración" title="Información fiscal" description="Estos datos identifican a la organización como cliente y se guardan como snapshot al emitir nuevas facturas." actions={<ActionButton variant="secondary" icon={RefreshCw} onClick={load}>Recargar</ActionButton>}/>
 <section className="nexus-metric-grid"><SurfaceCard><div className="flex items-center justify-between gap-3"><div><small className="text-[var(--app-text-muted)]">Estado del perfil</small><h2 className="text-xl mt-2">{profile.profile_status==='complete'?'Completo':'Incompleto'}</h2></div><StatusBadge tone={profile.profile_status==='complete'?'success':'warning'}>{profile.profile_status==='complete'?'Listo para facturación':'Requiere datos'}</StatusBadge></div></SurfaceCard><SurfaceCard><div className="flex items-center gap-3"><ShieldCheck className="text-[var(--app-primary)]"/><div><small className="text-[var(--app-text-muted)]">Versión fiscal</small><h2 className="text-xl mt-1">{Number(profile.profile_version||0)}</h2></div></div></SurfaceCard></section>
 {missing.length>0&&<SurfaceCard className="nexus-unsaved-banner"><div className="flex items-start gap-3"><AlertTriangle size={20}/><div><strong>Información obligatoria pendiente</strong><p className="mt-1">{missing.map(field=>fieldLabels[field]||field).join(', ')}.</p></div></div></SurfaceCard>}
 <SurfaceCard><div className="flex items-center gap-3 mb-5"><Building2 className="text-[var(--app-primary)]"/><div><h2 className="text-xl">Perfil fiscal de la organización</h2><p className="text-sm text-[var(--app-text-secondary)]">Las ediciones futuras no alteran facturas históricas.</p></div></div>
 <form className="nexus-guided-form" onSubmit={save}>
 <label><FieldGuide label="Tipo de persona" hint="Clasificación legal del titular." example="Persona jurídica" optional/><select value={profile.person_type||''} onChange={e=>set('person_type',e.target.value)}><option value="">Seleccionar</option><option value="persona_juridica">Persona jurídica</option><option value="persona_natural">Persona natural</option></select></label>
 <label><FieldGuide label="Nombre comercial" hint="Nombre visible del establecimiento." example="Centro de Bienestar Integral" optional/><input value={profile.commercial_name||''} onChange={e=>set('commercial_name',e.target.value)} maxLength={180}/></label>
 <label><FieldGuide label="Razón social" hint="Nombre legal usado en documentos tributarios." example="Centro de Bienestar Integral S.A.S." required/><input value={profile.legal_name||''} onChange={e=>set('legal_name',e.target.value)} maxLength={180}/></label>
 <label><FieldGuide label="Tipo de documento" hint="Documento fiscal del titular." example="NIT" required/><select value={profile.document_type||''} onChange={e=>set('document_type',e.target.value)}><option value="">Seleccionar</option><option value="NIT">NIT</option><option value="CC">Cédula de ciudadanía</option><option value="CE">Cédula de extranjería</option><option value="PASSPORT">Pasaporte</option><option value="OTHER">Otro</option></select></label>
 <label><FieldGuide label="Número de identificación" hint="Incluye separadores sólo si forman parte del documento." example="900123456-7" required/><input value={profile.tax_id||''} onChange={e=>set('tax_id',e.target.value)} maxLength={80}/></label>
 <label><FieldGuide label="Dígito de verificación" hint="Cuando aplique al NIT." example="7" optional/><input value={profile.verification_digit||''} onChange={e=>set('verification_digit',e.target.value)} maxLength={4}/></label>
 <label><FieldGuide label="Responsabilidad tributaria" hint="Responsabilidad declarada ante la autoridad fiscal." example="Responsable de IVA" optional/><input value={profile.tax_responsibility||''} onChange={e=>set('tax_responsibility',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Régimen fiscal" hint="Clasificación tributaria vigente." example="Régimen ordinario" optional/><input value={profile.tax_regime||''} onChange={e=>set('tax_regime',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Correo de facturación" hint="Recibirá documentos y comunicaciones de cobro." example="facturacion@empresa.com" required/><input type="email" value={profile.billing_email||''} onChange={e=>set('billing_email',e.target.value)} required/></label>
 <label><FieldGuide label="Contacto de facturación" hint="Persona responsable de revisar cobros." example="Laura Gómez" required/><input value={profile.billing_contact_name||''} onChange={e=>set('billing_contact_name',e.target.value)} required maxLength={120}/></label>
 <label><FieldGuide label="Teléfono del contacto" hint="Incluye indicativo de país." example="+57 300 123 4567" optional/><input value={profile.billing_contact_phone||''} onChange={e=>set('billing_contact_phone',e.target.value)} maxLength={40}/></label>
 <label><FieldGuide label="País" example="Colombia" optional/><input value={profile.country||''} onChange={e=>set('country',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Departamento" example="Antioquia" optional/><input value={profile.department||''} onChange={e=>set('department',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Ciudad" example="Medellín" required/><input value={profile.city||''} onChange={e=>set('city',e.target.value)} maxLength={120}/></label>
 <label className="nexus-field-wide"><FieldGuide label="Dirección fiscal" hint="Dirección completa usada en documentos de cobro." example="Carrera 43A # 10-25, local 201" required/><input value={profile.address||''} onChange={e=>set('address',e.target.value)} maxLength={240}/></label>
 <label><FieldGuide label="Código postal" example="050021" optional/><input value={profile.postal_code||''} onChange={e=>set('postal_code',e.target.value)} maxLength={20}/></label>
 <label><FieldGuide label="Correos en copia" hint="Separa varios correos con comas." example="contabilidad@empresa.com, gerencia@empresa.com" optional/><input value={profile.cc_emails||''} onChange={e=>set('cc_emails',e.target.value)}/></label>
 <label className="nexus-field-wide"><FieldGuide label="Notas fiscales internas" hint="Información administrativa; no debe contener secretos." example="Enviar soporte al cierre de cada mes" optional/><textarea value={profile.fiscal_notes||''} onChange={e=>set('fiscal_notes',e.target.value)} maxLength={1000}/></label>
 <label className="nexus-field-wide"><FieldGuide label="Motivo de la actualización" hint="Quedará registrado en la auditoría fiscal." example="Actualización anual de datos tributarios" required/><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} required/></label>
 <div className="nexus-field-wide flex flex-wrap gap-3"><ActionButton type="submit" icon={Save} loading={saving}>Guardar información fiscal</ActionButton><ActionButton type="button" variant="secondary" disabled={saving} onClick={load}>Descartar cambios</ActionButton></div>
 </form></SurfaceCard></MotionPage>;
}
