/* NEXUS_8A3B_THIRD_PARTY_MATRIX_UI_V1 */
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Building2,ChevronLeft,ChevronRight,FileCheck2,FileWarning,RefreshCw,Search,Users} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {toast} from 'sonner';
import {thirdPartyMatrixAPI} from '../api';
import {ActionButton,AnimatedNumber,DetailDrawer,EmptyState,MetricCard,MotionPage,PageHeader,ResponsiveDataView,SegmentedControl,StatusBadge,SurfaceCard} from '../components/design';
const labels={complete:'Completo',incomplete:'Incompleto'};const tones={complete:'success',incomplete:'warning'};
const fieldLabels={legal_name:'Razón social',document_type:'Tipo de documento',tax_id:'Identificación',billing_email:'Correo de facturación',city:'Ciudad',address:'Dirección'};
const safeDetail=e=>typeof e?.response?.data?.detail==='string'?e.response.data.detail:'No fue posible cargar la Matriz de terceros';
export default function OwnerThirdPartyMatrix(){
 const navigate=useNavigate();const [rows,setRows]=useState([]),[page,setPage]=useState(1),[meta,setMeta]=useState({page:1,page_size:25,total:0,total_pages:1}),[query,setQuery]=useState(''),[applied,setApplied]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[detailLoading,setDetailLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await thirdPartyMatrixAPI.list({page,page_size:25,search:applied||undefined,profile_status:status==='all'?undefined:status});setRows(r.data.items||[]);setMeta(r.data)}catch(e){toast.error(safeDetail(e))}finally{setLoading(false)}},[page,applied,status]);useEffect(()=>{load()},[load]);
 const visible=useMemo(()=>({complete:rows.filter(x=>x.profile_status==='complete').length,incomplete:rows.filter(x=>x.profile_status==='incomplete').length,people:rows.reduce((s,x)=>s+Number(x.people_count||0),0)}),[rows]);
 const search=e=>{e.preventDefault();setPage(1);setApplied(query.trim())};const changeStatus=v=>{setStatus(v);setPage(1)};
 const open=async item=>{setDetailLoading(true);setSelected({organization:item,loading:true});try{const r=await thirdPartyMatrixAPI.detail(item.organization_id);setSelected(r.data)}catch(e){setSelected(null);toast.error(safeDetail(e))}finally{setDetailLoading(false)}};
 const columns=[{key:'organization',label:'Organización',render:x=><button className="nexus-owner-user" onClick={()=>open(x)}><span>{(x.name||'?').charAt(0).toUpperCase()}</span><div><strong>{x.name||'Sin nombre'}</strong><small>{x.legal_name||x.organization_id}</small></div></button>},{key:'tax',label:'Identificación',render:x=>x.tax_id||'Pendiente'},{key:'status',label:'Estado fiscal',render:x=><StatusBadge tone={tones[x.profile_status]}>{labels[x.profile_status]}</StatusBadge>},{key:'people',label:'Personas',render:x=>x.people_count||0},{key:'city',label:'Ciudad',render:x=>x.city||'Pendiente'},{key:'actions',label:'Acción',align:'right',render:x=><ActionButton variant="ghost" onClick={()=>open(x)}>Ver detalle</ActionButton>}];
 return <MotionPage className="nexus-owner-page space-y-6"><PageHeader eyebrow="Administración Owner" title="Matriz de terceros" description="Consulta organizaciones, estado fiscal y personas vinculadas mediante una proyección segura." actions={<ActionButton variant="secondary" icon={RefreshCw} onClick={load}>Actualizar</ActionButton>}/>
 <section className="grid grid-cols-2 xl:grid-cols-4 gap-3"><MetricCard label="Resultados" value={<AnimatedNumber value={meta.total||0} format={v=>Math.round(v)}/>} icon={Building2}/><MetricCard label="Completos visibles" value={<AnimatedNumber value={visible.complete} format={v=>Math.round(v)}/>} icon={FileCheck2}/><MetricCard label="Incompletos visibles" value={<AnimatedNumber value={visible.incomplete} format={v=>Math.round(v)}/>} icon={FileWarning}/><MetricCard label="Personas visibles" value={<AnimatedNumber value={visible.people} format={v=>Math.round(v)}/>} icon={Users}/></section>
 <SurfaceCard><div className="nexus-owner-toolbar"><form onSubmit={search}><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, razón social, NIT, correo, ciudad o ID"/></label></form><SegmentedControl value={status} onChange={changeStatus} options={[{value:'all',label:'Todos'},{value:'complete',label:'Completos'},{value:'incomplete',label:'Incompletos'}]}/></div>
 {loading?<div className="nexus-loading-state"><div className="nexus-skeleton-row"/><div className="nexus-skeleton-row"/></div>:<ResponsiveDataView items={rows} columns={columns} rowKey={x=>x.organization_id} empty={<EmptyState icon={Building2} title="Sin organizaciones" description="Ajusta la búsqueda o el filtro fiscal."/>} renderCard={x=><button className="w-full text-left" onClick={()=>open(x)}><div className="flex justify-between gap-3"><strong>{x.name}</strong><StatusBadge tone={tones[x.profile_status]}>{labels[x.profile_status]}</StatusBadge></div><p>{x.legal_name||x.organization_id}</p><small>{x.people_count||0} persona(s) · {x.city||'Ciudad pendiente'}</small></button>}/>}
 <div className="flex justify-between items-center gap-3 mt-5"><small>Página {meta.page||1} de {meta.total_pages||1} · {meta.total||0} resultado(s)</small><div className="flex gap-2"><ActionButton variant="secondary" icon={ChevronLeft} disabled={!meta.has_previous||loading} onClick={()=>setPage(p=>Math.max(1,p-1))}>Anterior</ActionButton><ActionButton variant="secondary" icon={ChevronRight} disabled={!meta.has_next||loading} onClick={()=>setPage(p=>p+1)}>Siguiente</ActionButton></div></div></SurfaceCard>
 <DetailDrawer open={!!selected} onClose={()=>setSelected(null)} title={selected?.organization?.name||'Detalle del tercero'} description={selected?.organization?.organization_id}>{selected&&<div className="space-y-5">{detailLoading||selected.loading?<p>Cargando detalle...</p>:<><div className="nexus-detail-list">{[['Estado fiscal',labels[selected.fiscal_profile?.profile_status]],['Razón social',selected.fiscal_profile?.legal_name||'Pendiente'],['Identificación',selected.fiscal_profile?.tax_id||'Pendiente'],['Correo',selected.fiscal_profile?.billing_email||'Pendiente'],['Ciudad',selected.fiscal_profile?.city||'Pendiente'],['Personas',selected.people_count||0]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{selected.fiscal_profile?.missing_required_fields?.length>0&&<div><strong>Campos pendientes</strong><p>{selected.fiscal_profile.missing_required_fields.map(x=>fieldLabels[x]||x).join(', ')}</p></div>}<div><strong>Personas vinculadas</strong><ul className="nexus-audit-list">{(selected.people||[]).map(p=><li key={p.user_id}><strong>{p.name||'Sin nombre'}</strong><span>{p.role} · {p.email||'Sin correo'}</span><StatusBadge tone={p.access_status==='approved'?'success':'warning'}>{p.access_status||'Sin estado'}</StatusBadge></li>)}</ul></div><div className="nexus-drawer-actions"><ActionButton onClick={()=>navigate(`/manager/fiscal-profile?org_id=${selected.organization.organization_id}`)}>Editar información fiscal</ActionButton></div></>}</div>}</DetailDrawer></MotionPage>;
}
