/* NEXUS_8A7B_ORGANIZATION_ONBOARDING_UI_V1 */
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,Building2,CheckCircle2,RefreshCw,Save,ShieldCheck,UserRoundCheck} from 'lucide-react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {toast} from 'sonner';
import {organizationAPI,ownerAPI} from '../api';
import {ActionButton,FieldGuide,LoadingState,MotionPage,PageHeader,StatusBadge,SurfaceCard} from '../components/design';

const initial={name:'',manager_user_id:'',address:'',phone:'',whatsapp_link:'',business_hours:'',reason:'Alta inicial aprobada por Owner',fiscal_profile:{billing_email:'',billing_contact_name:'',billing_contact_phone:'',person_type:'',commercial_name:'',legal_name:'',document_type:'',tax_id:'',verification_digit:'',tax_responsibility:'',tax_regime:'',country:'Colombia',department:'',city:'',address:'',postal_code:'',fiscal_notes:'',cc_emails:[],copy_primary_manager:true,email_enabled:true}};
const required=[['name','Nombre de la organización'],['manager_user_id','Manager responsable'],['fiscal_profile.legal_name','Razón social'],['fiscal_profile.document_type','Tipo de documento'],['fiscal_profile.tax_id','Número de identificación'],['fiscal_profile.billing_email','Correo de facturación'],['fiscal_profile.billing_contact_name','Contacto de facturación'],['fiscal_profile.city','Ciudad'],['fiscal_profile.address','Dirección fiscal'],['reason','Motivo del alta']];
const detail=(e,fallback)=>{const d=e?.response?.data?.detail;if(typeof d==='string')return d;if(d?.missing_required_fields?.length)return `${d.message||fallback}: ${d.missing_required_fields.join(', ')}`;if(d?.message)return d.message;return fallback};
const isValidEmail=value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());
const get=(o,path)=>path.split('.').reduce((v,k)=>v?.[k],o);
export default function OwnerOrganizationOnboarding(){
 const navigate=useNavigate();const [searchParams]=useSearchParams();const requestedManagerId=searchParams.get('manager_user_id')||'';const [form,setForm]=useState(initial),[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[review,setReview]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await ownerAPI.getUsers();setUsers(r.data||[])}catch(e){toast.error(detail(e,'No fue posible cargar los Managers'))}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const managers=useMemo(()=>users.filter(x=>['manager','admin'].includes(x.role)&&x.access_status==='approved'&&x.active!==false&&!x.deleted_at&&!x.organization_id),[users]);
 const pending=useMemo(()=>users.filter(x=>['manager','admin'].includes(x.role)&&x.access_status==='pending'&&!x.organization_id),[users]);
  useEffect(()=>{if(!requestedManagerId)return;const eligible=managers.some(x=>x.user_id===requestedManagerId);if(eligible){setForm(current=>current.manager_user_id?current:{...current,manager_user_id:requestedManagerId});}},[requestedManagerId,managers]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));const setFiscal=(key,value)=>setForm(v=>({...v,fiscal_profile:{...v.fiscal_profile,[key]:value}}));
 const missing=useMemo(()=>required.filter(([path])=>!String(get(form,path)||'').trim()).map(([,label])=>label),[form]);
 const manager=managers.find(x=>x.user_id===form.manager_user_id);
 const submit=async()=>{if(missing.length)return toast.error(`Completa: ${missing.join(', ')}`);if(!isValidEmail(form.fiscal_profile.billing_email))return toast.error('Ingresa un correo de facturación válido');setSaving(true);try{const fiscalProfilePayload={...form.fiscal_profile,billing_email:form.fiscal_profile.billing_email.trim(),billing_contact_name:form.fiscal_profile.billing_contact_name.trim(),billing_contact_phone:form.fiscal_profile.billing_contact_phone?.trim()||null,commercial_name:form.fiscal_profile.commercial_name?.trim()||null,legal_name:form.fiscal_profile.legal_name.trim(),tax_id:form.fiscal_profile.tax_id.trim(),city:form.fiscal_profile.city.trim(),address:form.fiscal_profile.address.trim(),cc_emails:[]};const payload={...form,name:form.name.trim(),reason:form.reason.trim(),address:form.address.trim()||null,phone:form.phone.trim()||null,whatsapp_link:form.whatsapp_link.trim()||null,business_hours:form.business_hours.trim()||null,fiscal_profile:fiscalProfilePayload};const r=await organizationAPI.create(payload);toast.success('Organización creada con Manager y perfil fiscal');navigate(`/owner/third-party-matrix?created=${r.data.organization.organization_id}`)}catch(e){toast.error(detail(e,'No fue posible crear la organización'))}finally{setSaving(false)}};
 if(loading)return <LoadingState label="Cargando Managers disponibles"/>;
 return <MotionPage className="nexus-owner-page space-y-6"><PageHeader eyebrow="Administración Owner" title="Nueva organización" description="Crea el tercero, vincula un Manager aprobado y registra su perfil fiscal en una única operación segura." actions={<ActionButton variant="secondary" icon={ArrowLeft} onClick={()=>navigate('/owner/third-party-matrix')}>Volver a la matriz</ActionButton>}/>
 <section className="grid md:grid-cols-3 gap-3"><SurfaceCard><small>Managers elegibles</small><h2 className="text-2xl mt-2">{managers.length}</h2></SurfaceCard><SurfaceCard><small>Managers pendientes</small><h2 className="text-2xl mt-2">{pending.length}</h2></SurfaceCard><SurfaceCard><small>Suscripción y factura</small><h2 className="text-lg mt-2">No se crean automáticamente</h2></SurfaceCard></section>
 {requestedManagerId&&form.manager_user_id===requestedManagerId&&<SurfaceCard className="nexus-unsaved-banner"><div className="flex items-start gap-3"><UserRoundCheck/><div><strong>Manager preseleccionado de forma segura</strong><p className="mt-1">Revisa la organización y completa la información fiscal. La organización no se creará hasta la confirmación final.</p></div></div></SurfaceCard>}
  {!managers.length&&<SurfaceCard className="nexus-unsaved-banner"><div className="flex items-start gap-3"><AlertTriangle/><div><strong>No hay Managers aprobados y libres</strong><p className="mt-1">Aprueba primero una cuenta Manager pendiente. Un usuario ya asignado no puede moverse desde este flujo.</p><div className="mt-4 flex gap-2"><ActionButton onClick={()=>navigate('/owner/access-control')}>Ir a Control de accesos</ActionButton><ActionButton variant="secondary" icon={RefreshCw} onClick={load}>Actualizar</ActionButton></div></div></div></SurfaceCard>}
 <SurfaceCard><form className="nexus-guided-form" onSubmit={e=>{e.preventDefault();setReview(true)}}>
 <div className="nexus-field-wide"><h2 className="text-xl">1. Organización y responsable</h2><p className="text-sm text-[var(--app-text-secondary)]">El Owner global no será reasignado. El Manager seleccionado debe estar aprobado y sin organización.</p></div>
 <label><FieldGuide label="Nombre de la organización" hint="Nombre visible en Nexus." example="Nueva Organización" required/><input value={form.name} onChange={e=>set('name',e.target.value)} maxLength={180} required/></label>
 <label><FieldGuide label="Manager responsable" hint="Sólo aparecen Managers aprobados y libres." example="Laura Gómez · manager@empresa.com" required/><select value={form.manager_user_id} onChange={e=>set('manager_user_id',e.target.value)} disabled={!managers.length} required><option value="">Seleccionar Manager</option>{managers.map(x=><option key={x.user_id} value={x.user_id}>{x.name||'Sin nombre'} · {x.email}</option>)}</select></label>
 <label><FieldGuide label="Teléfono comercial" hint="Incluye indicativo de país." example="+57 300 123 4567" optional/><input value={form.phone} onChange={e=>set('phone',e.target.value)} maxLength={40}/></label>
 <label><FieldGuide label="Enlace de WhatsApp" example="https://wa.me/573001234567" optional/><input value={form.whatsapp_link} onChange={e=>set('whatsapp_link',e.target.value)} maxLength={500}/></label>
 <div className="nexus-field-wide"><h2 className="text-xl mt-4">2. Información fiscal obligatoria</h2><p className="text-sm text-[var(--app-text-secondary)]">Estos datos habilitan la emisión futura. No se crea ninguna factura durante el alta.</p></div>
 <label><FieldGuide label="Razón social" example="Nueva Organización SAS" required/><input value={form.fiscal_profile.legal_name} onChange={e=>setFiscal('legal_name',e.target.value)} maxLength={180} required/></label>
 <label><FieldGuide label="Nombre comercial" example="Nueva Organización" optional/><input value={form.fiscal_profile.commercial_name} onChange={e=>setFiscal('commercial_name',e.target.value)} maxLength={180}/></label>
 <label><FieldGuide label="Tipo de documento" example="NIT" required/><select value={form.fiscal_profile.document_type} onChange={e=>setFiscal('document_type',e.target.value)} required><option value="">Seleccionar</option><option value="NIT">NIT</option><option value="CC">Cédula de ciudadanía</option><option value="CE">Cédula de extranjería</option><option value="PASSPORT">Pasaporte</option><option value="OTHER">Otro</option></select></label>
 <label><FieldGuide label="Número de identificación" example="900123456" required/><input value={form.fiscal_profile.tax_id} onChange={e=>setFiscal('tax_id',e.target.value)} maxLength={80} required/></label>
 <label><FieldGuide label="Correo de facturación" hint="Recibirá comunicaciones de cobro cuando se habiliten." example="facturacion@empresa.com" required/><input type="email" value={form.fiscal_profile.billing_email} onChange={e=>setFiscal('billing_email',e.target.value)} required/></label>
 <label><FieldGuide label="Contacto de facturación" example="Laura Gómez" required/><input value={form.fiscal_profile.billing_contact_name} onChange={e=>setFiscal('billing_contact_name',e.target.value)} maxLength={120} required/></label>
 <label><FieldGuide label="País" example="Colombia" optional/><input value={form.fiscal_profile.country} onChange={e=>setFiscal('country',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Departamento" example="Antioquia" optional/><input value={form.fiscal_profile.department} onChange={e=>setFiscal('department',e.target.value)} maxLength={120}/></label>
 <label><FieldGuide label="Ciudad" example="Medellín" required/><input value={form.fiscal_profile.city} onChange={e=>setFiscal('city',e.target.value)} maxLength={120} required/></label>
 <label className="nexus-field-wide"><FieldGuide label="Dirección fiscal" example="Calle 10 # 20-30" required/><input value={form.fiscal_profile.address} onChange={e=>setFiscal('address',e.target.value)} maxLength={240} required/></label>
 <label className="nexus-field-wide"><FieldGuide label="Motivo del alta" hint="Quedará registrado en auditoría." example="Alta inicial aprobada por Owner" required/><textarea value={form.reason} onChange={e=>set('reason',e.target.value)} minLength={10} maxLength={500} required/></label>
 <div className="nexus-field-wide flex gap-3"><ActionButton type="submit" icon={ShieldCheck} disabled={!managers.length||missing.length>0}>Revisar alta</ActionButton><ActionButton type="button" variant="secondary" onClick={()=>navigate('/owner/third-party-matrix')}>Cancelar</ActionButton></div>
 </form></SurfaceCard>
 {review&&<SurfaceCard><div className="flex items-start gap-3"><CheckCircle2 className="text-[var(--app-success)]"/><div className="flex-1"><h2 className="text-xl">Confirmación final</h2><p className="mt-2">Se creará <strong>{form.name}</strong>, se vinculará a <strong>{manager?.name||'Manager pendiente'}</strong> y se guardará el perfil fiscal de <strong>{form.fiscal_profile.legal_name}</strong>.</p><ul className="mt-3 text-sm"><li>No se moverá al Owner global.</li><li>No se crearán suscripción, factura ni correo.</li><li>La operación tendrá rollback y auditoría.</li></ul><div className="mt-4 flex gap-3"><ActionButton icon={Save} loading={saving} disabled={missing.length>0} onClick={submit}>Crear organización</ActionButton><ActionButton variant="secondary" disabled={saving} onClick={()=>setReview(false)}>Volver a editar</ActionButton></div></div></div></SurfaceCard>}
 </MotionPage>;
}
