import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {CreditCard,FileText,History,RefreshCw,Save,WalletCards} from 'lucide-react';
import {toast} from 'sonner';
import {organizationAPI,subscriptionAPI} from '../api';
import {ActionButton,AdminShell,EmptyState,FieldGuide,LoadingState,MetricCard,MotionPage,PageHeader,StatusBadge,SurfaceCard} from '../components/design';

const statuses={trial:'Prueba',active:'Activa',grace_period:'Periodo de gracia',past_due:'Vencida',suspended:'Suspendida',cancelled:'Cancelada',indefinite_block:'Bloqueo indefinido'};
const invoiceLabels={draft:'Borrador',issued:'Emitida',pending:'Pendiente',paid:'Pagada',overdue:'Vencida',void:'Anulada',refunded:'Reembolsada'};
const isoDay=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const asIso=(value)=>value?`${value}T12:00:00+00:00`:'';
const money=(minor,currency='COP')=>new Intl.NumberFormat('es-CO',{style:'currency',currency,maximumFractionDigits:0}).format((Number(minor)||0)/100);
const detail=(error,fallback)=>error.response?.data?.detail||fallback;

export default function OwnerSubscriptions(){
 const [orgs,setOrgs]=useState([]),[orgId,setOrgId]=useState(''),[subscription,setSubscription]=useState(null),[invoices,setInvoices]=useState([]),[audit,setAudit]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const [form,setForm]=useState({plan_code:'nexus_monthly',monthly_amount:'150000',currency:'COP',billing_day:1,status:'active',reason:'Configuración mensual de la organización'});
 const [invoice,setInvoice]=useState({period_start:isoDay(0).slice(0,8)+'01',period_end:isoDay(30),due_at:isoDay(10),amount:'150000',currency:'COP',notes:'Factura mensual'});
 const selected=useMemo(()=>orgs.find(x=>x.organization_id===orgId),[orgs,orgId]);
 const load=useCallback(async(id)=>{if(!id)return;setLoading(true);try{const [s,i,a]=await Promise.all([subscriptionAPI.get(id).catch(e=>e.response?.status===200?e:({data:null})),subscriptionAPI.getInvoices(id),subscriptionAPI.getAudit(id,{limit:100})]);setSubscription(s.data);setInvoices(i.data||[]);setAudit(a.data||[]);if(s.data)setForm({plan_code:s.data.plan_code,monthly_amount:String((s.data.monthly_amount_minor||0)/100),currency:s.data.currency,billing_day:s.data.billing_day,status:s.data.status,reason:'Actualización administrativa de la suscripción'});}catch(e){toast.error(detail(e,'No fue posible cargar las suscripciones'))}finally{setLoading(false)}},[]);
 useEffect(()=>{organizationAPI.getAll().then(r=>{const rows=r.data||[];setOrgs(rows);if(rows[0])setOrgId(rows[0].organization_id)}).catch(e=>toast.error(detail(e,'No fue posible cargar organizaciones')))},[]);
 useEffect(()=>{if(orgId)load(orgId)},[orgId,load]);
 const save=async(e)=>{e.preventDefault();setBusy('subscription');try{await subscriptionAPI.save(orgId,{plan_code:form.plan_code.trim(),monthly_amount_minor:Math.round(Number(form.monthly_amount)*100),currency:form.currency.toUpperCase(),billing_day:Number(form.billing_day),status:form.status,reason:form.reason.trim()});toast.success('Suscripción guardada');await load(orgId)}catch(err){toast.error(detail(err,'No fue posible guardar'))}finally{setBusy('')}};
 const createInvoice=async(e)=>{e.preventDefault();setBusy('invoice');try{await subscriptionAPI.createInvoice(orgId,{period_start:asIso(invoice.period_start),period_end:asIso(invoice.period_end),due_at:asIso(invoice.due_at),amount_minor:Math.round(Number(invoice.amount)*100),currency:invoice.currency.toUpperCase(),notes:invoice.notes||null});toast.success('Factura emitida');await load(orgId)}catch(err){toast.error(detail(err,'No fue posible emitir la factura'))}finally{setBusy('')}};
 const pay=async(row)=>{const reference=window.prompt('Referencia del pago manual');if(!reference)return;setBusy(row.invoice_id);try{await subscriptionAPI.confirmManualPayment(orgId,row.invoice_id,{amount_minor:row.amount_minor,currency:row.currency,provider_reference:reference,idempotency_key:`ui-${row.invoice_id}-${reference}`.slice(0,200),notes:'Confirmado desde administración Owner'});toast.success('Pago confirmado');await load(orgId)}catch(err){toast.error(detail(err,'No fue posible confirmar el pago'))}finally{setBusy('')}};
 const pending=invoices.filter(x=>['draft','issued','pending','overdue'].includes(x.status));
 return <AdminShell organizationName={selected?.name||'Nexus'} organizationId={orgId}><MotionPage><PageHeader eyebrow="Owner" title="Suscripciones" description="Administra planes, facturación mensual y pagos manuales por organización." actions={<ActionButton icon={RefreshCw} onClick={()=>load(orgId)}>Actualizar</ActionButton>}/>
 <SurfaceCard><label><FieldGuide label="Organización" hint="Selecciona el tenant que deseas administrar." required/><select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option key={o.organization_id} value={o.organization_id}>{o.name}</option>)}</select></label></SurfaceCard>
 {loading?<LoadingState label="Cargando suscripción"/>:<><div className="nexus-metric-grid"><MetricCard label="Estado" value={statuses[subscription?.status]||'Sin configurar'} icon={CreditCard}/><MetricCard label="Valor mensual" value={subscription?money(subscription.monthly_amount_minor,subscription.currency):'$ 0'} icon={WalletCards}/><MetricCard label="Facturas pendientes" value={pending.length} icon={FileText}/><MetricCard label="Eventos de auditoría" value={audit.length} icon={History}/></div>
 <div className="nexus-subscription-grid"><SurfaceCard><h2>Configuración mensual</h2><form className="nexus-guided-form" onSubmit={save}><label><FieldGuide label="Código del plan" hint="Identificador estable del plan contratado." example="nexus_monthly" required/><input value={form.plan_code} onChange={e=>setForm({...form,plan_code:e.target.value})} required/></label><label><FieldGuide label="Valor mensual" unit="COP" hint="Escribe pesos completos. Nexus almacena el valor en centavos." example="150000" required/><input type="number" min="0" step="1" value={form.monthly_amount} onChange={e=>setForm({...form,monthly_amount:e.target.value})} required/></label><label><FieldGuide label="Moneda" example="COP" required/><input maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})} required/></label><label><FieldGuide label="Día de cobro" hint="Entre 1 y 28 para evitar fechas inexistentes." required/><input type="number" min="1" max="28" value={form.billing_day} onChange={e=>setForm({...form,billing_day:e.target.value})} required/></label><label><FieldGuide label="Estado" required/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="nexus-field-wide"><FieldGuide label="Motivo" hint="Quedará registrado en auditoría." required/><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/></label><ActionButton type="submit" icon={Save} disabled={busy==='subscription'}>{busy==='subscription'?'Guardando…':'Guardar suscripción'}</ActionButton></form></SurfaceCard>
 <SurfaceCard><h2>Emitir factura</h2><form className="nexus-guided-form" onSubmit={createInvoice}>{[['period_start','Inicio del periodo'],['period_end','Fin del periodo'],['due_at','Fecha límite']].map(([k,l])=><label key={k}><FieldGuide label={l} required/><input type="date" value={invoice[k]} onChange={e=>setInvoice({...invoice,[k]:e.target.value})} required/></label>)}<label><FieldGuide label="Valor de la factura" unit="COP" required/><input type="number" min="0" step="1" value={invoice.amount} onChange={e=>setInvoice({...invoice,amount:e.target.value})} required/></label><label><FieldGuide label="Moneda" required/><input maxLength="3" value={invoice.currency} onChange={e=>setInvoice({...invoice,currency:e.target.value})} required/></label><label className="nexus-field-wide"><FieldGuide label="Notas" optional/><textarea value={invoice.notes} onChange={e=>setInvoice({...invoice,notes:e.target.value})}/></label><ActionButton type="submit" icon={FileText} disabled={!subscription||busy==='invoice'}>Emitir factura</ActionButton></form></SurfaceCard></div>
 <SurfaceCard><h2>Facturas</h2>{!invoices.length?<EmptyState icon={FileText} title="Sin facturas" description="Emite la primera factura mensual para esta organización."/>:<div className="nexus-table-wrap"><table className="nexus-table"><thead><tr><th>Periodo</th><th>Vence</th><th>Valor</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{invoices.map(row=><tr key={row.invoice_id}><td>{row.period_start?.slice(0,10)} a {row.period_end?.slice(0,10)}</td><td>{row.due_at?.slice(0,10)}</td><td>{money(row.amount_minor,row.currency)}</td><td><StatusBadge tone={row.status==='paid'?'success':row.status==='overdue'?'danger':'warning'}>{invoiceLabels[row.status]||row.status}</StatusBadge></td><td>{row.status==='paid'?<span>Pago confirmado</span>:['void','refunded'].includes(row.status)?<span>Sin acciones</span>:<ActionButton onClick={()=>pay(row)} disabled={busy===row.invoice_id}>Confirmar pago</ActionButton>}</td></tr>)}</tbody></table></div>}</SurfaceCard>
 <SurfaceCard><h2>Auditoría reciente</h2>{!audit.length?<EmptyState icon={History} title="Sin eventos" description="Los cambios y pagos aparecerán aquí."/>:<ul className="nexus-audit-list">{audit.map(x=><li key={x.audit_event_id}><strong>{x.event_type}</strong><span>{x.reason}</span><time>{String(x.created_at).replace('T',' ').slice(0,19)}</time></li>)}</ul>}</SurfaceCard></>}</MotionPage></AdminShell>;
}
