import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, CreditCard, Loader2, WalletCards } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { barberAPI, transactionAPI } from '../api';
// NEXUS_REVENUE_MODULE_V1
const METHODS={cash:'Efectivo',card:'Tarjeta',transfer:'Transferencia',nequi:'Nequi',daviplata:'Daviplata',other:'Otro'};
const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:2}).format(Number(v)||0);
const date=d=>new Date(Date.now()-d*86400000).toISOString().split('T')[0];
export default function RevenueDashboard(){
 const {user}=useAuth(),navigate=useNavigate(),[sp]=useSearchParams(); const org=sp.get('org_id')||user?.organization_id;
 const [filters,setFilters]=useState({start_date:date(30),end_date:date(0),barber_id:'',payment_method:''}),[items,setItems]=useState([]),[summary,setSummary]=useState(null),[barbers,setBarbers]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null);
 const params=useMemo(()=>{const p={organization_id:org,start_date:filters.start_date,end_date:filters.end_date,limit:500};if(filters.barber_id)p.barber_id=filters.barber_id;if(filters.payment_method)p.payment_method=filters.payment_method;return p},[org,filters]);
 useEffect(()=>{if(!org)return;setLoading(true);Promise.all([transactionAPI.getAll(params),transactionAPI.getSummary(params),barberAPI.getAll(user?.role==='owner'?{organization_id:org}:{})]).then(([a,b,c])=>{setItems(a.data||[]);setSummary(b.data);setBarbers(c.data||[])}).finally(()=>setLoading(false))},[org,params,user?.role]);
 const back=user?.role==='owner'&&org?`/manager/dashboard?org_id=${org}`:'/manager/dashboard';
 const cards=summary?[['Total recibido',summary.total_received],['Servicios netos',summary.total_net_service_amount],['Comisiones Staff',summary.total_staff_commission],['Participación negocio',summary.total_business_amount],['Propinas',summary.total_tips],['Descuentos',summary.total_discount],['Ticket promedio',summary.average_ticket],['Transacciones',summary.transaction_count]]:[];
 return <div className="min-h-screen bg-black text-white"><header className="sticky top-0 z-40 bg-black/90 border-b border-white/10 p-4"><div className="max-w-7xl mx-auto flex items-center gap-3"><button onClick={()=>navigate(back)} className="flex gap-2 text-zinc-400"><ArrowLeft/>Volver</button>{/* NEXUS_STAFF_SETTLEMENTS_UI_V1 */}<button onClick={()=>navigate(user?.role==='owner'&&org?`/manager/settlements?org_id=${org}`:'/manager/settlements')} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-300"><CreditCard size={18}/>Liquidaciones</button><div className="text-right ml-auto"><h1 className="text-2xl">Ingresos</h1><p className="text-xs text-zinc-500">Cobros y comisiones</p></div></div></header><main className="max-w-7xl mx-auto p-4 space-y-6">
 <section className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 p-4 bg-white/5 rounded-2xl border border-white/10"><input type="date" value={filters.start_date} onChange={e=>setFilters({...filters,start_date:e.target.value})} className="p-3 bg-zinc-900 rounded-xl"/><input type="date" value={filters.end_date} onChange={e=>setFilters({...filters,end_date:e.target.value})} className="p-3 bg-zinc-900 rounded-xl"/><select value={filters.barber_id} onChange={e=>setFilters({...filters,barber_id:e.target.value})} className="p-3 bg-zinc-900 rounded-xl"><option value="">Todos los profesionales</option>{barbers.map(x=><option key={x.barber_id} value={x.barber_id}>{x.display_name||x.name}</option>)}</select><select value={filters.payment_method} onChange={e=>setFilters({...filters,payment_method:e.target.value})} className="p-3 bg-zinc-900 rounded-xl"><option value="">Todos los pagos</option>{Object.entries(METHODS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>setFilters({start_date:date(30),end_date:date(0),barber_id:'',payment_method:''})} className="p-3 bg-white/10 rounded-xl">Limpiar</button></section>
 {loading?<div className="py-20 flex justify-center"><Loader2 className="animate-spin"/></div>:<><section className="grid grid-cols-2 lg:grid-cols-4 gap-3">{cards.map(([a,b])=><div key={a} className="p-4 bg-white/5 rounded-2xl border border-white/10"><WalletCards className="text-emerald-400 mb-2"/><p className="text-xl">{a==='Transacciones'?b:money(b)}</p><p className="text-xs text-zinc-400">{a}</p></div>)}</section><section className="bg-white/5 rounded-2xl border border-white/10"><div className="p-5 border-b border-white/10"><h2 className="text-lg">Historial de ingresos</h2><p className="text-sm text-zinc-500">{items.length} cobros</p></div>{items.length?items.map(x=><button key={x.transaction_id} onClick={()=>setSelected(x)} className="w-full p-4 border-b border-white/5 flex justify-between text-left"><div><p>{x.service_name_snapshot}</p><p className="text-sm text-zinc-400">{x.barber_name_snapshot} · {METHODS[x.payment_method]}</p><p className="text-xs text-zinc-500">{new Date(x.created_at).toLocaleString('es-CO')}</p></div><b className="text-emerald-400">{money(x.total_received)}</b></button>):<p className="p-16 text-center text-zinc-500">No hay cobros.</p>}</section></>}
 </main>{selected&&<div className="fixed inset-0 z-50 bg-black/80 p-4 flex items-center justify-center"><div className="max-w-lg w-full bg-zinc-950 rounded-2xl p-6"><button onClick={()=>setSelected(null)} className="float-right">Cerrar</button><h2 className="text-xl mb-5">Detalle del cobro</h2>{[['Servicio',selected.service_name_snapshot],['Profesional',selected.barber_name_snapshot],['Precio original',money(selected.service_price_snapshot)],['Descuento',money(selected.discount_amount)],['Valor neto',money(selected.net_service_amount)],['Comisión Staff',money(selected.staff_commission_amount)],['Participación negocio',money(selected.business_amount)],['Propina',money(selected.tip_amount)],['Total recibido',money(selected.total_received)],['Pago',METHODS[selected.payment_method]],['ID',selected.transaction_id]].map(([a,b])=><div key={a} className="flex justify-between gap-3 py-1"><span className="text-zinc-500">{a}</span><span className="text-right">{b}</span></div>)}</div></div>}</div>;
}
