import React,{useEffect,useState} from 'react';
import {Building2,Plus,Search,Truck} from 'lucide-react';
import {supplierAPI} from '../api';
import {MotionPage,PageHeader,SurfaceCard,MetricCard,ActionButton,StatusBadge,EmptyState,LoadingState,AccessibleModal} from '../components/design';
import {toast} from 'sonner';
const blank={business_name:'',legal_name:'',tax_id:'',contact_name:'',phone:'',email:'',address:'',city:'',payment_terms:'',payment_term_days:0,usual_lead_time_days:0,notes:''};
export default function SuppliersDashboard(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await supplierAPI.getAll({search,page_size:100});setItems(r.data.items||[])}catch(e){toast.error(e.response?.data?.detail||'No fue posible cargar proveedores')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);const submit=async()=>{if(!form.business_name.trim())return toast.error('Escribe el nombre comercial');setSaving(true);try{await supplierAPI.create({...form,payment_term_days:Number(form.payment_term_days),usual_lead_time_days:Number(form.usual_lead_time_days)});toast.success('Proveedor creado');setForm(blank);setOpen(false);await load()}catch(e){toast.error(e.response?.data?.detail?.message||e.response?.data?.detail||'No fue posible crear el proveedor')}finally{setSaving(false)}};
 return <MotionPage><PageHeader eyebrow="Abastecimiento" title="Proveedores" description="Directorio comercial y base para órdenes de compra." actions={<ActionButton icon={Plus} onClick={()=>setOpen(true)}>Nuevo proveedor</ActionButton>}/><div className="nexus-metric-grid"><MetricCard label="Activos" value={items.filter(x=>x.active).length} icon={Building2}/><MetricCard label="Inactivos" value={items.filter(x=>!x.active).length} icon={Truck}/></div><SurfaceCard><div className="nexus-toolbar"><div className="nexus-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Buscar proveedor, razón social o NIT"/></div><ActionButton variant="secondary" onClick={load}>Buscar</ActionButton></div>{loading?<LoadingState label="Cargando proveedores"/>:items.length?<div className="nexus-supplier-grid">{items.map(x=><article key={x.supplier_id} className="nexus-supplier-card"><div><h3>{x.business_name}</h3><p>{x.legal_name||x.contact_name||'Sin contacto registrado'}</p></div><StatusBadge tone={x.active?'success':'neutral'}>{x.active?'Activo':'Inactivo'}</StatusBadge><dl><div><dt>NIT</dt><dd>{x.tax_id||'No registrado'}</dd></div><div><dt>Entrega</dt><dd>{x.usual_lead_time_days||0} días</dd></div><div><dt>Pago</dt><dd>{x.payment_term_days||0} días</dd></div></dl></article>)}</div>:<EmptyState icon={Building2} title="Aún no hay proveedores" description="Crea el primer proveedor para preparar compras y abastecimiento."/>}</SurfaceCard><AccessibleModal open={open} onClose={()=>setOpen(false)} labelledBy="supplier-title"><section className="nexus-void-modal nexus-supplier-modal"><h2 id="supplier-title">Nuevo proveedor</h2><div className="nexus-form-grid">{[['business_name','Nombre comercial'],['legal_name','Razón social'],['tax_id','NIT o identificación'],['contact_name','Contacto'],['phone','Teléfono'],['email','Correo'],['city','Ciudad'],['address','Dirección'],['payment_terms','Condiciones de pago'],['payment_term_days','Días de pago'],['usual_lead_time_days','Plazo de entrega']].map(([k,l])=><label key={k}>{l}<input type={k.includes('days')?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="span-2">Notas<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer><ActionButton variant="secondary" onClick={()=>setOpen(false)}>Cancelar</ActionButton><ActionButton loading={saving} onClick={submit}>Guardar proveedor</ActionButton></footer></section></AccessibleModal></MotionPage>}
